### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by timoxley** [millermedeiros/js-signals#20]
Have you tried this out with nodejs before? You should get a version into the nodejs package management tool http://npmjs.org/

**Comment by millermedeiros** [comment]
I will take a look on it, but for now it isn't on my priority list. Thanks for the heads up.

**Comment by tomyan** [comment]
Also really interested in getting js-signals via npm (love the library btw). In particular I'd like to be able to depend on it from a couple of modules that I publish via npm. Let me know if there are any contributions I could make to help with this.

Thanks

Tom

**Comment by timoxley** [comment]
@tomyan, perhaps if you have the npm publishing knowhow, you could package signals in a forked signals branch and issue a pull request to @millermedeiros for your branch, which could then be submitted to npm? I'd do it but I haven't looked at publishing via npm yet so it may be easier for you to do it.

**Comment by tomyan** [comment]
See https://github.com/millermedeiros/js-signals/pull/21

Thanks

Tom

**Comment by millermedeiros** [comment]
ready to be used! http://search.npmjs.org/#/signals
