### ISSUE TITLE
add support to dispatch history / "message bus"

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/js-signals#29]
One nice feature of [deferred/promises](http://wiki.commonjs.org/wiki/Promises) is that you can add listeners after a promise was already resolved and it will still pass arguments supplied on the `resolve` call... 

[Postman](http://www.aaron-powell.com/javascript/postman) have a feature called "message bus" which also keeps record of last dispatch and gives the option to listen to a message previously dispatched.

It may be a nice addition to signals as well, but I think the default behavior should remain the same, getting value from a previously dispatched signal should be an opt-in feature.

**Comment by millermedeiros** [comment]
I thought a lot about it and I think the best way to implement it is by creating a new kind of Signal, that way we avoid storing references to unneeded values and also make it harder to mess with the default behavior of third-party code (since it may break things badly). I also think that creating a new Signal type will make it clearer that it works differently.

proposal:

``` js
//AsyncSignal keeps previous dispatch "in memory"
var intialized = new signals.AsyncSignal();

//won't log anything for now since signal wasn't dispatched yet
initialized.add(function(t){
  console.log('1: '+ t);
});

//log "1: lorem-ipsum"
initialized.dispatch('lorem-ipsum');

//will log "2: lorem-ipsum" even tho the signal was dispatched before adding the listener
initialized.add(function(t){
  console.log('2: '+ t);
});

//log "1: foo"
//log "2: foo"
initialized.dispatch('foo');

//will log "3: foo" (it uses previous dispatched value if it does exist)
initialized.add(function(t){
  console.log('3: '+ t);
});
```

can probably re-use most of the regular `Signal` logic and just augment `add`, `addOnce` and `dispatch` logic.

**Comment by millermedeiros** [comment]
see [diff between branches](https://github.com/millermedeiros/js-signals/compare/master...iss29#diff-23) to understand what changed.

**Comment by ghost** [comment]
I would use a message bus!

**Comment by millermedeiros** [comment]
maybe add a public method `reset()` to clear `_prevParams`... it will increase flexibility.

**Comment by millermedeiros** [comment]
decided to simplify the logic.. instead of creating a new kind of signal just created a new public property `memorize`.

``` js
var intialized = new signals.Signal();
initialized.memorize = true; //default is `false`
```

way less code and simpler to use.. (this is JavaScript! not Java!)

merged into the [develop](https://github.com/millermedeiros/js-signals/tree/develop) branch.
