### ISSUE TITLE
create unit tests for node

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/js-signals#31]
probably just switch unit tests to qunit and use https://github.com/jdalton/qunit-clib

**Comment by millermedeiros** [comment]
jasmine seems a good option as well: http://pivotal.github.com/jasmine/

**Comment by millermedeiros** [comment]
definitely use jasmine for tests.. really liked the syntax and the idea of describing what code should do, helped me to find some edge cases on another project... only problem now is to find time to port all tests..

**Comment by millermedeiros** [comment]
If someone want to help I've created a tool to help the process: http://millermedeiros.github.com/YUI_to_Jasmine/

use [crossroads specs](https://github.com/millermedeiros/crossroads.js/tree/master/dev/tests/spec) as reference

**Comment by millermedeiros** [comment]
This can simplify unit tests a lot: https://github.com/AdamNowotny/js-signals-logger

**Comment by AdamNowotny** [comment]
Just improved js-signal-logger and created new project https://github.com/AdamNowotny/jasmine-signals
This should be even easier to use with Jasmine.

**Comment by millermedeiros** [comment]
@AdamNowotny nice! this task is on my todo list since forever. will use jasmine-signals for sure, will be good to clean the tests. Thanks for sharing it.

**Comment by AdamNowotny** [comment]
You can find sample usage at https://github.com/AdamNowotny/BuildReactor, I'll keep this project up-to-date with jasmine-signals.
This should make it easier to configure js-signals, jasmine and require-js (just follow the SpecRunner.html file) and get started with the specs :) Note I'm including js-signals, jasmine and jasmine-signals in the page and not as AMD module.

**Comment by millermedeiros** [comment]
In the end I didn't refactored it to use jasmine-signals since it was simpler to just apply some RegExp and macros. I removed some redundant specs and improved others as well. I added a link to jasmine-signals on the README. Cheers!
