### ISSUE TITLE
getters and setters for memorize/active/params? Object.freeze by default?

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/js-signals#51]
I kinda regret of using normal properties instead of getter/setters because JS doesn't complain when we try to set a property that doesn't exist - `signal.memoize = true;` will be extremely hard to spot (missing `r`).

It could be fixed by "use strict" + `Object.freeze()` on ES5:

``` js
"use strict";

var changed = new Signal();
Object.freeze(changed);

changed.memoize = true; // throw error since `memoize` doesn't exist
```

I heard that `Object.freeze` have some perf impact on V8 but that should be fixed soon.

One option would be to freeze the Signal and SignalBinding automatically during the instantiation but that might prevent users from adding custom behavior to a Signal instance (will reduce the flexibility).

My current opinion is that we should leave it as is to keep backwards compatibility and maybe do getters/setters for a v2.0 release.

**Comment by drkibitz** [comment]
keep as is. My autocomplete works ;)
I don't know if v8 will fix the perf impact.
And getters and setters introduce and unnecessary function call for most people.
I use events for a lot, including games, which must dispatch quite a few signals at 60 fps. Introducing extra function calls can hurt things quite a big in these situations.

**Comment by millermedeiros** [comment]
The getters/setters would be just for these 3 properties:

``` js
changed.memorize(true);
changed.active(true);
changed.defaultArguments(123, 456);
```

They aren't that common tho... just putting the thoughts out there so in the future we remind why it wasn't coded like this and what I was thinking at the time... Outside feedback is great for putting these things in perspective.

**Comment by millermedeiros** [comment]
ahh, forgot to say.. another option would be add a "flag" to signals to toggle the behavior, something like a `signals.neuroticMode = true;` which would make all signals to be _frozen_ during instantiation... no backwards incompatibility and just a way to enhance development... (could be disabled before deploy) would also not cause issues if used in previous versions (it would fail silently - no side effects)

**Comment by r4j4h** [comment]
Sounds like you are on the right track but just wanted to add another outside perspective's concern for performance hits. :) (Even if v8 ameliorates performance hits that doesn't help other browsers' JS engines)

**Comment by millermedeiros** [comment]
closing this in favor of #60
