### ISSUE TITLE
convert signal instance into a function

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/js-signals#53]
functions are first class objects in JavaScript, I find it unnecessary that we need to call `myObj.mySignal.add(handler)` when we could simply do it like `myObj.mySignal(handler)`.

`mySignal()` would be just a shortcut for `mySignal.add()` (we wouldn't remove `mySignal.add`).

PS: this is just an idea that I had based on the amount of mistakes I commit while trying to add a listener, specially when the signal have a name like `clicked` or `started`.

I will wait for feedback.

**Comment by andy-law** [comment]
My initial thought on that is that it could become more confusing, as I'd expect calling mySignal() would more likely dispatch the signal than subscribe to it.

**Comment by drkibitz** [comment]
-1

**Comment by millermedeiros** [comment]
I agree that this doesn't seem like a good idea. Like @andy-law said it can be confusing. Closing it.
