### ISSUE TITLE
Conflicts when using signals in a instance of a class

### ISSUE THREAD

**Issue by stefanoortisi** [millermedeiros/js-signals#56]
If I store the signal as a simple instance variable everything just works fine.
Instead if I store the signal as a property of an object which is a variable instance of the object, then if I create two different instance of the wrapper class, the second instance has already the signal instantiated (and this shouldn't happen!)

The first pastebin shows the right version
http://pastebin.com/hxLaKM4R

The second pastebin shows the wrong version
http://pastebin.com/T3S2hczJ

**Comment by millermedeiros** [comment]
that is because all instances of `Emitter` share the same object `on` (objects are passed by reference even if defined on the prototype). You need to create the `on` object inside the constructor.
