### ISSUE TITLE
Add package to bower

### ISSUE THREAD

**Issue by auchenberg** [millermedeiros/js-signals#57]
Lately I started using `bower` for our client-side dependencies. To streamline the setup on how the dependencies are resolved, it would be helpful if you also added a package to `bower`

Other libraries that can be used in a both a node and browser context, like [q](https://github.com/kriskowal/q) has exposed packages in both dependency managers.

**Comment by millermedeiros** [comment]
I added a `bower.json` file and removed some unnecessary files and updated git tag v1.0.0 to match latest changes.

please confirm if that works for you:

``` sh
bower install js-signals
```

**Comment by auchenberg** [comment]
Confirmed. 

Awesome, thanks! :sunglasses:
