### ISSUE TITLE
can you give us some examples?

### ISSUE THREAD

**Issue by changfuguo** [millermedeiros/js-signals#61]
i want to use this plugin,but can you give us some examples ??tks

**Comment by wookieb** [comment]
IMO this examples are fine https://github.com/millermedeiros/js-signals/wiki/Examples

**Comment by changfuguo** [comment]
tks so much ~~very helpful ~~~

------------------ 原始邮件 ------------------
发件人: "Łukasz Kużyński";notifications@github.com;
发送时间: 2014年7月9日(星期三) 凌晨3:08
收件人: "millermedeiros/js-signals"js-signals@noreply.github.com; 
抄送: "聂风"changfuguo@qq.com; 
主题: Re: [js-signals] can you give us some examples? (#61)

IMO these examples are fine https://github.com/millermedeiros/js-signals/wiki/Examples
